### ISSUE TITLE
The extension not working for me

### ISSUE THREAD

**Issue by joserprieto** [nbehier/bolt-cookie-consent#3]
Hi:

I tried to install the extension, but not working.

My configs:

./composer.json:

```
{
    "name": "joserprieto/arte-et-marte-website",
    "description": "Arte et Marte website made with Bolt CMS, sophisticated, lightweight & simple CMS",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": "^5.5.9 || ^7.0",
        "bolt/bolt": "^3.0@beta",
        "PasswordLib/PasswordLib": "^1.0@beta"
    },
    "minimum-stability": "beta",
    "prefer-stable": true,
    "scripts": {
        "post-install-cmd": [
            "Bolt\\Composer\\ScriptHandler::installAssets"
        ],
        "post-update-cmd": [
            "Bolt\\Composer\\ScriptHandler::installAssets"
        ],
        "post-create-project-cmd": [
            "Bolt\\Composer\\ScriptHandler::configureProject",
            "Bolt\\Composer\\ScriptHandler::installThemesAndFiles",
            "nut extensions:setup"
        ]
    },
    "extra": {
        "branch-alias": {
            "dev-master": "3.0-dev"
        }
    }
}
```

./extensions/composer.json

```
{
    "autoload": {
        "psr-4": {
            "Bolt\\Composer\\EventListener\\": "../vendor/bolt/bolt/src/Composer/EventListener"
        }
    },
    "config": {
        "discard-changes": true,
        "preferred-install": "dist"
    },
    "description": "Bolt extension installation interface",
    "extra": {
        "bolt-web-path": "../web",
        "bolt-root-path": ".."
    },
    "license": "MIT",
    "minimum-stability": "stable",
    "name": "bolt/extensions",
    "prefer-stable": true,
    "provide": {
        "bolt/bolt": "3.0.4"
    },
    "repositories": {
        "packagist": false,
        "bolt": {
            "type": "composer",
            "url": "https://extensions.bolt.cm/satis/"
        }
    },
    "scripts": {
        "post-autoload-dump": "Bolt\\Composer\\EventListener\\PackageEventListener::dump",
        "post-package-install": "Bolt\\Composer\\EventListener\\PackageEventListener::handle",
        "post-package-update": "Bolt\\Composer\\EventListener\\PackageEventListener::handle"
    },
    "require": {
        "bobdenotter/seo": "v0.10.1",
        "bolt/disqus": "v2.0.1",
        "bolt/sitemap": "2.0.0"
    }
}
```

I tried to install manually with composer require leskis/cookie-consent && composer update
The website crashes, and i got a 500 internal server error.

Other configs:

$ uname --all
Linux Asimov 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jan 14 2016 17:45:23

$ php -v
PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans
    with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo

$ mysql --version
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3

$ composer --version
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Composer version 1.2-dev (bdb9c5f22f9b4ebcffeff3844c3cb4d1d3232da8) 2016-04-29 16:46:27

**Comment by nbehier** [comment]
I tried few days ago to update this extension, but didn't succeed neither. I hope I'll find time in a week or two to find the bug...

**Comment by MMelisseOmniboost** [comment]
When I try to install it, the installation won't work anymore. Need to remove dir manually and run composer update again... :(

**Comment by nbehier** [comment]
OK, I got it ! Release v2.0.4 fixes last bugs. Be carefull, _AdBlock_ has to be inactivate to install or config extension… and It seems it blocks cookie consent on frontend by default :-(
